app:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/supra
      username: root
      password: r
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  flyway:
    enabled: false